### ISSUE TITLE
 Building pages with patterns problem

### ISSUE THREAD

**Issue by RukiyaS** [RukiyaS/ecommerce-pattern-library#2]
@thomasjbradley

I’m working on the Building pages with patterns exercise and my banner is covering my footer

**Comment by thomasjbradley** [comment]
Try adding `overflow: hidden` to the `.hero-image` CSS.

**Comment by RukiyaS** [comment]
@thomasjbradley I'm trying to change the image for the product page banner and add the highlight nav but both aren't working

**Comment by thomasjbradley** [comment]
Are you seeing any error messages in Terminal? All the code looks okay—from what I can see.

**Comment by RukiyaS** [comment]
There was and I fixed it. Now the banner images are showing but the highlight nav still isn't working @thomasjbradley

**Comment by RukiyaS** [comment]
nevermind, I got it working. I finished this exercise.

**Comment by thomasjbradley** [comment]
👍
