### ISSUE TITLE
Building pages with patterns lesson

### ISSUE THREAD

**Issue by RukiyaS** [RukiyaS/ecommerce-pattern-library#3]
I'm on the last step for the Building pages with patterns lesson which is to highlight nav and I did it but it's not working

@MacKenzieRose

**Comment by MacKenzieRose** [comment]
Hey Rukiya,

Not sure if it will fully fix it, but in your nav.html file (under your navigations patterns), your 3 if's (lines 11, 12, and 13) aren't closed, which is causing rendering errors. 

You'll need them to be in this format:
<img width="652" alt="Screen Shot 2020-03-27 at 5 36 00 PM" src="https://user-images.githubusercontent.com/19557909/77802552-7cff7600-7051-11ea-95c4-a39a5e05f9bd.png">


Let me know if that helps.

**Comment by RukiyaS** [comment]
@MacKenzieRose

it's still not working

**Comment by MacKenzieRose** [comment]
Some other things I can see:

1) Your patterns/headers config file doesn't have a src field, but your banner.html file has a {{include.src}}  for the image;

2) The class of current for the <li> tags doesn't have any new styling applied to it in the css file, so you won't see any changes. I put this as a placeholder, just to test if it's working:
<img width="171" alt="Screen Shot 2020-03-27 at 6 53 12 PM" src="https://user-images.githubusercontent.com/19557909/77806836-467b2880-705c-11ea-9e58-999b2d9466da.png">

3) Your brackets for your class need to close after your endif statement (see below):
<img width="651" alt="Screen Shot 2020-03-27 at 6 54 49 PM" src="https://user-images.githubusercontent.com/19557909/77806906-77f3f400-705c-11ea-86f7-5cc23edd3e2d.png">

4) And finally, on your index.html page, you'll need to include a "highlight_nav: home" section to see a change between your home and products pages.

I've got it working on my end, but let me know how it goes :)

**Comment by RukiyaS** [comment]
on your end do you see the current page link have a dot underneath like in the example? Because mine isn't showing a dot.

<img width="957" alt="Screen Shot 2020-03-27 at 7 12 01 PM" src="https://user-images.githubusercontent.com/43240582/77807672-f2be0e80-705e-11ea-8003-7eea2c947176.png">
<img width="1507" alt="Screen Shot 2020-03-27 at 7 12 12 PM" src="https://user-images.githubusercontent.com/43240582/77807681-f5b8ff00-705e-11ea-9f83-ce7b1dac7cc9.png">

**Comment by MacKenzieRose** [comment]
The dot is just how Thomas styled his navigation; unless you've added it into your own CSS, you shouldn't see one.

Is everything else working so far?

**Comment by RukiyaS** [comment]
ohh okay, everything else is working. Thank you so much for the help

**Comment by MacKenzieRose** [comment]
If this issue has been resolved, feel free to close it :)

Cheers!
MacKenzie
